title: Make a data plotter with LEGO and Build HAT
hero_image: images/banner.png
description: my-private-repo description
version: 4
listed: false
copyedit: false
last_tested: "2020-10-27"
steps:
  - title: Introduction
  - title: Moving the motors with data
  - title: Creating a plot range
  - title: Building the plotter
  - title: Paper feeding
  - title: Button control
  - title: Adding a real-time data source
  - title: What next?
