title: Make a data plotter with LEGO and Build HAT
hero_image: images/banner.png
description: my-private-repo description
version: 4
listed: false
copyedit: false
last_tested: "2020-10-27"
steps:
  - title: Introduction
  - title: Simulated data
  - title: Building the plotter
  - title: Paper feeding and button control
  - title: Adding a real data source
  - title: What next?
