---
title: LEGO® data plotter
hero_image: images/banner.png
description: Plot data with pen and paper, using LEGO® and the Build HAT
version: 4
listed: true
copyedit: true
last_tested: '2020-10-27'
steps:
- title: Introduction
- title: Move the motors with data
- title: Create a plot range
  completion:
  - engaged
- title: Build the plotter
- title: Feed in paper
- title: Add a button control
- title: Add a real-time data source
  completion:
  - internal
- title: What next?
  completion:
  - external
