---
title: LEGO® data plotter
hero_image: images/banner.png
description: Plot data with pen and paper, using LEGO® and the Build HAT
version: 4
listed: true
copyedit: true
last_tested: "2020-10-27"
steps:
  - 
    title: Introduction
  - 
    title: Move the motors with data
  - 
    title: Create a plot range
  - 
    title: Build the plotter
  - 
    title: Paper feeding
  - 
    title: Button control
  - 
    title: Adding a real-time data source
  - 
    title: What next?
