---
title: LEGO® Datenplotter
hero_image: images/banner.png
description: Zeichne Daten mit Stift und Papier mit LEGO® und dem Build HAT
version: 4
listed: true
copyedit: true
last_tested: "2020-10-27"
steps:
  - 
    title: Einleitung
  - 
    title: Bewege die Motoren mit Daten
  - 
    title: Erstelle einen Plotbereich
  - 
    title: Baue den Plotter
  - 
    title: Feed in paper
  - 
    title: Add a button control
  - 
    title: Hinzufügen einer Echtzeit-Datenquelle
  - 
    title: Wie geht es weiter?
